<a href="https://colab.research.google.com/github/vafiyanaznin/business-analytics-along-with-python/blob/main/sample_supermarket.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [9]:
df=pd.read_excel("/content/Sample - Superstore.xlsx")
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.2480,3,0.20,4.1028
9990,9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.9600,2,0.00,15.6332
9991,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.5760,2,0.20,19.3932
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.6000,4,0.00,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.1600,2,0.00,72.9480

In [11]:
df.Sales.max()

22638.48

In [13]:
df.Sales.min()

0.44399999999999995

In [18]:
df.Sales.count()

9994

In [20]:
df.Sales.sum()

2297200.8603000003

In [22]:
df.Sales.sum()/9994

229.85800083049833

In [26]:
df.groupby("Quantity").max()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,9988,US-2017-167920,2017-12-29,2018-01-03,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004959,Technology,Tables,iOttie HLCRIO102 Car Mount,1270.990,0.8,635.4950
2,9994,US-2017-169551,2017-12-30,2018-01-05,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,4799.984,0.8,1995.9900
3,9990,US-2017-169551,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,York,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,10499.970,0.8,5039.9856
4,9993,US-2017-168802,2017-12-30,2018-01-04,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wyoming,98661,West,TEC-PH-10004977,Technology,Tables,netTALK DUO VoIP Telephone Service,13999.960,0.8,6719.9808
5,9989,US-2017-169502,2017-12-29,2018-01-02,Standard Class,ZD-21925,Zuschuss Donatelli,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004977,Technology,Tables,invisibleSHIELD by ZAGG Smudge-Free Screen Pro...,17499.950,0.8,8399.9760
6,9948,US-2017-167402,2017-12-28,2017-12-31,Standard Class,YS-21880,Yana Sorensen,Home Office,United States,Yuma,Wisconsin,99301,West,TEC-PH-10004922,Technology,Tables,iOttie HLCRIO102 Car Mount,22638.480,0.8,1453.1238
7,9983,US-2017-165344,2017-12-30,2018-01-04,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yuma,Wisconsin,99207,West,TEC-PH-10004977,Technology,Tables,Zebra GX420t Direct Thermal/Thermal Transfer P...,9099.930,0.8,2400.9657
8,9949,US-2017-158526,2017-12-29,2018-01-05,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Yonkers,Wisconsin,99301,West,TEC-PH-10004531,Technology,Tables,Zipper Ring Binder Pockets,8159.952,0.8,1459.2000
9,9943,US-2017-166688,2017-12-25,2018-01-01,Standard Class,ZC-21910,Zuschuss Carroll,Home Office,United States,Wilmington,Wisconsin,99207,West,TEC-PH-10004667,Technology,Tables,netTALK DUO VoIP Telephone Service,5399.910,0.8,2591.9568
10,9985,US-2017-165344,2017-12-04,2017-12-09,Standard Class,VT-21700,Valerie Takahito,Home Office,United States,Tucson,Washington,98226,West,TEC-PH-10004614,Technology,Tables,iKross Bluetooth Portable Keyboard + Cell Phon...,4007.840,0.8,394.2680
11,9896,US-2017-142188,2017-11-28,2017-12-02,Standard Class,TT-21460,Tonja Turnell,Home Office,United States,Vacaville,Wisconsin,98115,West,TEC-PH-10002834,Technology,Storage,Xerox 232,2888.127,0.7,767.2005
12,8871,US-2017-110576,2017-12-01,2017-12-06,Standard Class,XP-21865,Xylona Preis,Home Office,United States,Tulsa,Washington,98270,West,TEC-PH-10002496,Technology,Tables,"Wirebound Message Books, Four 2 3/4 x 5 White ...",3610.848,0.4,561.5640
13,9883,US-2017-147669,2017-12-25,2017-12-30,Standard Class,VP-21760,Victoria Pisteka,Home Office,United States,Woodstock,Washington,98103,West,TEC-PH-10004833,Technology,Tables,Xerox 1952,9892.740,0.8,4946.3700
14,9980,US-2017-155425,2017-12-14,2017-12-18,Standard Class,TG-21640,Trudy Glocke,Home Office,United States,Tucson,Washington,98103,West,TEC-PH-10001557,Technology,Storage,Xerox 1964,1819.860,0.8,510.6360

In [27]:
df.groupby("Quantity").count()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Discount,Profit
Quantity,,,,,,,,,,,,,,,,,,,,
1,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899,899
2,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402,2402
3,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409,2409
4,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191,1191
5,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230,1230
6,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572,572
7,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606,606
8,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257
9,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258,258
10,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57,57
11,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34
12,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23
13,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27
14,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29

In [28]:
df.groupby("Ship Mode").count()

,Row ID,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
Ship Mode,,,,,,,,,,,,,,,,,,,,
First Class,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538,1538
Same Day,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543,543
Second Class,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945,1945
Standard Class,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968,5968

In [32]:
df.groupby("State").Sales.mean()

State
Alabama                  319.846557
Arizona                  157.508933
Arkansas                 194.635500
California               228.729451
Colorado                 176.418231
Connecticut              163.223866
Delaware                 285.948635
District of Columbia     286.502000
Florida                  233.612815
Georgia                  266.825217
Idaho                    208.689810
Illinois                 162.939230
Indiana                  359.431946
Iowa                     152.658667
Kansas                   121.429583
Kentucky                 263.250000
Louisiana                219.453095
Maine                    158.816250
Maryland                 225.766886
Massachusetts            212.106919
Michigan                 299.096525
Minnesota                335.541011
Mississippi              203.232830
Missouri                 336.441667
Montana                  372.623467
Nebraska                 196.445526
Nevada                   428.951333
New Hampshire            270.093481
New Jersey               275.110092
New Mexico               129.284378
New York                 275.599531
North Carolina           223.305880
North Dakota             131.415714
Ohio                     166.861697
Oklahoma                 298.233182
Oregon                   140.573790
Pennsylvania             198.487077
Rhode Island             404.070643
South Carolina           201.945476
South Dakota             109.630000
Tennessee                167.551219
Texas                    172.779742
Utah                     211.699170
Vermont                  811.760909
Virginia                 315.342500
Washington               273.994605
West Virginia            302.456000
Wisconsin                291.951000
Wyoming                 1603.136000
Name: Sales, dtype: float64

In [39]:
df.loc[df['Ship Mode']=="Second Class"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.940,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
17,18,CA-2014-167164,2014-05-13,2014-05-15,Second Class,AG-10270,Alejandro Grove,Consumer,United States,West Jordan,...,84084,West,OFF-ST-10000107,Office Supplies,Storage,Fellowes Super Stor/Drawer,55.500,2,0.0,9.9900
18,19,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,OFF-AR-10003056,Office Supplies,Art,Newell 341,8.560,2,0.0,2.4824
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9965,9966,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-PA-10000349,Office Supplies,Paper,Easy-staple paper,4.980,1,0.0,2.3406
9966,9967,CA-2016-146374,2016-12-05,2016-12-10,Second Class,HE-14800,Harold Engle,Corporate,United States,Newark,...,19711,East,OFF-EN-10004483,Office Supplies,Envelopes,"#10 White Business Envelopes,4 1/8 x 9 1/2",109.690,7,0.0,51.5543
9980,9981,US-2015-151435,2015-09-06,2015-09-09,Second Class,SW-20455,Shaun Weien,Consumer,United States,Lafayette,...,70506,South,FUR-TA-10001039,Furniture,Tables,KI Adjustable-Height Table,85.980,1,0.0,22.3548
9989,9990,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [43]:
df.loc[df["Category"] == "Office Supplies"]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
6,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
8,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
9,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9982,9983,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,OFF-PA-10002195,Office Supplies,Paper,"RSVP Cards & Envelopes, Blank White, 8-1/2"" X ...",35.560,7,0.0,16.7132
9984,9985,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-LA-10003766,Office Supplies,Labels,Self-Adhesive Removable Labels,31.500,10,0.0,15.1200
9985,9986,CA-2015-100251,2015-05-17,2015-05-23,Standard Class,DV-13465,Dianna Vittorini,Consumer,United States,Long Beach,...,11561,East,OFF-SU-10000898,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,55.600,4,0.0,16.1240
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480